### ISSUE TITLE
How to adjust page width?

### ISSUE THREAD

**Issue by capsl0cker** [vinitkumar/white-paper#26]
Hi there,
Thanks for making this great theme! I am using it and I like it.
But I have one question, how to adjust page width? I want to make page width smaller.
Or the page margin a little bigger. How to do it? I am an idiot of html/css.

**Comment by vinitkumar** [comment]
Hello @capsl0cker. Glad you like the theme.  Well, adjusting page-width is all about adjusting the padding of the container.

Take a look at this screenshot.

If you look closely, the container padding is changed to `padding: 0 120px 0 120px` from `padding: 0 20px;`. This will reduce the width of the page.  You can adjust this value as per your taste.


<img width="1410" alt="screenshot 2017-12-07 at 10 57 19 pm" src="https://user-images.githubusercontent.com/537678/33728908-085f8254-dba2-11e7-9134-847b27358750.png">

Here are the steps to get it implemented in code.
- Follow the steps here to set it up for local development (https://github.com/vinitkumar/white-paper#local-development)
- Now, update the CSS file, https://github.com/vinitkumar/white-paper/blob/a12de76f83f5782fbf1241b095e9683ebc513ba2/css/base.css#L69 as per the padding you want like the example I gave above.
- Next, just run `grunt css`, It will update the minified file with your changes and then just commit the code, it should just work.
