### ISSUE TITLE
How to add a blog post?

### ISSUE THREAD

**Issue by adarsh0112** [vinitkumar/white-paper#28]
Could you tell me how to add a blog post to the site?

**Comment by vinitkumar** [comment]
Hi @adarsh0112 If you check the repository, there is a folder called as _posts https://github.com/vinitkumar/white-paper/tree/gh-pages/_posts

Any file inside it is automatically picked up as post. But there is a condition.

The file must have the name in following way:

`2017-02-23-How-to-get-readonly-mode-in-django.md`

First date seperate by hyphen and then the title.

So if you want to create a post with filename new post and date today, the filename would be

`2017-02-08-New-Post.md`

Also, follow the following structure to create the post

```md
---
layout: post
title: "tile of the posts"
description: "description about the title"
category: articles
tags: [python, django, django-admin]
comments: false
---

Add the detailed post here

```

Hope, this answers your question, if you have any more question, just look the link above and try and figure out how it is done. Should be pretty straight forward.

**Comment by vinitkumar** [comment]
Okay, I hope my reply solved your query. I am closing this issue now.
