### ISSUE TITLE
Changing Font and CSS Styling

### ISSUE THREAD

**Issue by ichromanrd** [vinitkumar/white-paper#37]
Hi Vinit.

Really love your work on this theme. Since I am new to jekyll and I decided to use jekyll as my platform for blogging, then I want to change Jekyll default theme and found your theme. This is simple yet beautiful.

I want to change the font and some color on the link. I have put new font on css directory, and run **jekyll serve** but no changes made.

Am I missing something?

Regards,
Ichroman Raditya

**Comment by vinitkumar** [comment]
Hi,
Glad you are liking the theme. if you, look at the readme you will need to
have node.js installed and run 'grunt css' in the base directory for the
css to update.

Let me know if this works out for you? Also, try going a git push to your
branch and see it the code made it to your github.

Regards,
Vinit

**Comment by vinitkumar** [comment]
@ichromanrd Let me know if it worked fine for you?

**Comment by ichromanrd** [comment]
Hi @vinitkumar 

Yeah I just realized that there is gruntfile.js. Thanks! It works now.

**Comment by vinitkumar** [comment]
@ichromanrd Looks like your issue is resolved now. Closing this ticket now.
