### ISSUE TITLE
Footer ?

### ISSUE THREAD

**Issue by mrcat323** [vinitkumar/white-paper#47]
Nice theme.
but the problem is absence of footer

**Comment by mrcat323** [comment]
Man, @vinitkumar for example I didn't put my github username and etc, the footer disappears. Make a **exception**, for instance if there is no data of user just place footer and write there something like:
#### Copyright (c) sitename 2020

**Comment by vinitkumar** [comment]
Good tip. Thanks for your input.

**Comment by vinitkumar** [comment]
@mrcat323 Alright. Implemented it in the theme. 
<img width="893" alt="Screenshot 2020-01-22 at 7 59 25 PM" src="https://user-images.githubusercontent.com/537678/72902983-6c313c00-3d52-11ea-91c3-25b00d687437.png">
