### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by mrcat323** [vinitkumar/white-paper#50]
Hey @vinitkumar 
I'm a bit confused about pagination stuff in the **right bottom side** of post page
![image](https://user-images.githubusercontent.com/23054662/72966518-f9bb6d00-3de0-11ea-942f-f07c6842ad05.png)
I assume you made it in contrary, previous posts' (oldest let's say) chevron could be the right, I mean this one:
![image](https://user-images.githubusercontent.com/23054662/72966620-34bda080-3de1-11ea-96e0-28908ebe18d1.png)
It would be active when we're viewing _new posts_. And _**latest posts**_ **(new ones)** could be oppositely, the **left chevron**: 
![image](https://user-images.githubusercontent.com/23054662/72966698-5dde3100-3de1-11ea-878f-c1556749620c.png)
but here it's placed oppositely.

**Comment by vinitkumar** [comment]
@mrcat323 Cool. I think I like your suggestion. I can understand why it might be confusing to some. I will merge your PR.

**Comment by vinitkumar** [comment]
@mrcat323 I had to revert your changes. It looks like your implementation is a bit buggy. When you go to the second page, the back button should be active but it is not. Could you please look into the bug and fix it in a another PR where it works perfectly. I will be more than happy to merge it then.

**Comment by mrcat323** [comment]
@vinitkumar hey man, I had tested it in firefox and chrome, it works perfectly, the back button works
Here is the first page:
![image](https://user-images.githubusercontent.com/23054662/72983558-634c7300-3e03-11ea-909b-833067864340.png)
and here is the second:
![image](https://user-images.githubusercontent.com/23054662/72983608-7fe8ab00-3e03-11ea-9782-52b98e969ed3.png)

I cleared cache to make sure it isn't because of it. but it works, it is active

**Comment by mrcat323** [comment]
and reopen the issue, notifications don't come if you don't reopen it

**Comment by vinitkumar** [comment]
@mrcat323 You are right. It was cached so was showing the wrong result. Thanks for your contribution. I reapplied your changes so it is live now as well. 

Keep these nice contributions coming 🥂
